### ISSUE TITLE
The help message of claferIG does not explain how to change global scope

### ISSUE THREAD

**Issue by wasowski** [gsdlab/clafer#72]
The help message of claferIG does not explain how to change global scope (or where to find this kind of info). Probably just a single line telling how you can get help inside IG printed in response to --help or in the IG startup messages would reduce user frustration.  It took me some time to go the tools installation and to find the readme files.

**Comment by mantkiew** [comment]
I reposted to ClaferIG [issue](https://github.com/gsdlab/claferIG/issues/28).
