### ISSUE TITLE
Link broken for binary distribution?

### ISSUE THREAD

**Issue by chrismcgraw60** [gsdlab/clafer#93]
Hi,

I tried to access the binary distribution via the link on the wiki (and clafer.org) and I'm getting 404 Not Found.

Are the binaries still available?

Thanks.

**Comment by alex-murashkin** [comment]
Hi there, 
Could you try this link: http://gsd.uwaterloo.ca/clafer-tools-binary-distributions.html
The website has undergone some maintenance, and some links are still broken.

**Comment by chrismcgraw60** [comment]
Hi Alex, I was able to use that link fine. Thanks for the fast response.

**Comment by mantkiew** [comment]
We were switching from Apache to Nginx and in the process the part adding `.html` was broken. All fixed now (the old links were all without `.html` because it was Drupal, now we have static archive).
